import {
  Contract,
  rpc,
  TransactionBuilder,
  Networks,
  BASE_FEE,
  nativeToScVal,
  Address,
  Horizon,
} from "@stellar/stellar-sdk";
import { signTransaction } from "@stellar/freighter-api";

const RPC_URL = import.meta.env.VITE_STELLAR_RPC_URL || "https://soroban-testnet.stellar.org";
const CONTRACT_ID = import.meta.env.VITE_CONTRACT_ID as string;
const NETWORK_PASSPHRASE = Networks.TESTNET;

const server = new rpc.Server(RPC_URL);

// Use Horizon to fetch balances since RPC Server getAccount only gets sequence numbers
const horizonServer = new Horizon.Server("https://horizon-testnet.stellar.org");

export async function getWalletBalance(walletAddress: string): Promise<string> {
  try {
    const account = await horizonServer.loadAccount(walletAddress);
    const nativeBalance = account.balances.find((b) => b.asset_type === "native");
    return nativeBalance ? nativeBalance.balance : "0.00";
  } catch (err) {
    console.error("Error fetching balance:", err);
    return "0.00";
  }
}

/**
 * Converts a hex-encoded 32-byte challenge id (as generated by the backend)
 * into the raw Buffer Soroban expects for a BytesN<32> argument.
 */
function challengeIdToBytes(hexId: string): Uint8Array {
  const bytes = new Uint8Array(hexId.length / 2);
  for (let i = 0; i < hexId.length; i += 2) {
    bytes[i / 2] = parseInt(hexId.substring(i, i + 2), 16);
  }
  if (bytes.length !== 32) {
    throw new Error("contractChallengeId must decode to exactly 32 bytes");
  }
  return bytes;
}

/**
 * Builds, signs (via Freighter), and submits a Soroban contract invocation.
 * Returns the transaction hash once confirmed.
 */
async function invokeContract(
  method: string,
  args: ReturnType<typeof nativeToScVal>[],
  sourceAddress: string
): Promise<string> {
  if (!CONTRACT_ID) {
    throw new Error("VITE_CONTRACT_ID is not configured");
  }

  const account = await server.getAccount(sourceAddress);
  const contract = new Contract(CONTRACT_ID);

  let tx = new TransactionBuilder(account, {
    fee: BASE_FEE,
    networkPassphrase: NETWORK_PASSPHRASE,
  })
    .addOperation(contract.call(method, ...args))
    .setTimeout(60)
    .build();

  tx = await server.prepareTransaction(tx);

  const signResult = await signTransaction(tx.toXDR(), {
    networkPassphrase: NETWORK_PASSPHRASE,
  });

  if (!signResult) {
    throw new Error("Transaction signing was rejected or failed");
  }

  // Freighter API v2+ returns { signedTxXdr, signerAddress }; older versions return the XDR string directly.
  const signedXdr = typeof signResult === "object" && signResult !== null && "signedTxXdr" in signResult
    ? (signResult as { signedTxXdr: string }).signedTxXdr
    : (signResult as unknown as string);

  const signedTx = TransactionBuilder.fromXDR(signedXdr, NETWORK_PASSPHRASE);
  const sendResult = await server.sendTransaction(signedTx);

  if (sendResult.status === "ERROR") {
    throw new Error(`Transaction submission failed: ${sendResult.errorResult?.toString() ?? "unknown error"}`);
  }

  // Poll for confirmation
  let getResult = await server.getTransaction(sendResult.hash);
  let attempts = 0;
  while (getResult.status === "NOT_FOUND" && attempts < 15) {
    await new Promise((r) => setTimeout(r, 1500));
    getResult = await server.getTransaction(sendResult.hash);
    attempts += 1;
  }

  if (getResult.status !== "SUCCESS") {
    throw new Error(`Transaction did not succeed on-chain (status: ${getResult.status})`);
  }

  return sendResult.hash;
}

/** Creates a challenge on-chain. Called right after the backend record is created. */
export async function createChallengeOnChain(
  contractChallengeId: string,
  organizationAddress: string,
  rewardPoolStroops: bigint,
  maxWinners: number,
  deadlineUnixSeconds: number
): Promise<string> {
  const args = [
    nativeToScVal(challengeIdToBytes(contractChallengeId), { type: "bytes" }),
    new Address(organizationAddress).toScVal(),
    nativeToScVal(rewardPoolStroops, { type: "i128" }),
    nativeToScVal(maxWinners, { type: "u32" }),
    nativeToScVal(deadlineUnixSeconds, { type: "u64" }),
  ];
  return invokeContract("create_challenge", args, organizationAddress);
}

/** Funds (tops up) an existing on-chain challenge's reward pool. */
export async function fundChallengeOnChain(
  contractChallengeId: string,
  organizationAddress: string,
  amountStroops: bigint
): Promise<string> {
  const args = [
    nativeToScVal(challengeIdToBytes(contractChallengeId), { type: "bytes" }),
    new Address(organizationAddress).toScVal(),
    nativeToScVal(amountStroops, { type: "i128" }),
  ];
  return invokeContract("fund_challenge", args, organizationAddress);
}

/** Approves a learner's submission on-chain and records the reward. */
export async function approveSubmissionOnChain(
  contractChallengeId: string,
  organizationAddress: string,
  learnerAddress: string,
  rewardAmountStroops: bigint
): Promise<string> {
  const args = [
    nativeToScVal(challengeIdToBytes(contractChallengeId), { type: "bytes" }),
    new Address(organizationAddress).toScVal(),
    new Address(learnerAddress).toScVal(),
    nativeToScVal(rewardAmountStroops, { type: "i128" }),
  ];
  return invokeContract("approve_submission", args, organizationAddress);
}

/** Issues an on-chain achievement credential for an approved learner. */
export async function issueAchievementOnChain(
  contractChallengeId: string,
  organizationAddress: string,
  learnerAddress: string,
  credentialHashHex: string,
  rewardAmountStroops: bigint
): Promise<string> {
  const args = [
    nativeToScVal(challengeIdToBytes(contractChallengeId), { type: "bytes" }),
    new Address(organizationAddress).toScVal(),
    new Address(learnerAddress).toScVal(),
    nativeToScVal(
      new Uint8Array(credentialHashHex.match(/.{1,2}/g)!.map((byte) => parseInt(byte, 16))),
      { type: "bytes" }
    ),
    nativeToScVal(rewardAmountStroops, { type: "i128" }),
  ];
  return invokeContract("issue_achievement", args, organizationAddress);
}

/** XLM (7 decimal places) to stroops, for building i128 contract args. */
export function xlmToStroops(xlm: number): bigint {
  return BigInt(Math.round(xlm * 10_000_000));
}
